config/routes.rb
Myapp::Application.routes.draw do

  devise_for :users
  # You can have the root of your site routed with "root"
  root to: 'dashboards#index'

  resources :dashboards

  namespace :api do
    resources :datapoints
    authenticate :user do
      resources :probes
    end
  end


  authenticate :user do
    resources :probes
  end
  authenticate :user do
    resources :studies, only: [:create, :new, :edit, :update] do
      member do
        post 'join'
        post 'leave'
      end
    end
  end
  resources :studies, only: [:show, :index]
end

app/models/probe.rb
class Probe < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :user
  has_many :probe_datapoints, dependent: :destroy
end

class ProbeDatapoint < ActiveRecord::Base
  belongs_to :probe
  serialize :data
end

app/models/study.rb
class Study < ActiveRecord::Base
  belongs_to :user
  has_many :users
  has_many :instructions
  accepts_nested_attributes_for :instructions, reject_if: :all_blank

  def is_active
    self.end != nil and Time.now < self.end and self.start != nil and Time.now > self.start
  end

  def percent_done
    ((Time.now-self.start)/(self.end-self.start)*100).round
  end
end

class Instruction < ActiveRecord::Base
  belongs_to :Study
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :probe, dependent: :nullify
  has_one :hosted_study, dependent: :nullify, :class_name => "Study"
  belongs_to :study
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    protect_from_forgery with: :null_session
    before_action :set_resource, only: [:destroy, :show, :update]
    respond_to :json

    private

      # Returns the resource from the created instance variable
      # @return [Object]
      def get_resource
        instance_variable_get("@#{resource_name}")
      end

      # Returns the allowed parameters for searching
      # Override this method in each API controller
      # to permit additional parameters to search on
      # @return [Hash]
      def query_params
        {}
      end

      # Returns the allowed parameters for pagination
      # @return [Hash]
      def page_params
        params.permit(:page, :page_size)
      end

      # The resource class based on the controller
      # @return [Class]
      def resource_class
        @resource_class ||= resource_name.classify.constantize
      end

      # The singular name for the resource class based on the controller
      # @return [String]
      def resource_name
        @resource_name ||= self.controller_name.singularize
      end

      # Only allow a trusted parameter "white list" through.
      # If a single resource is loaded for #create or #update,
      # then the controller for the resource must implement
      # the method "#{resource_name}_params" to limit permitted
      # parameters for the individual model.
      def resource_params
        @resource_params ||= self.send("#{resource_name}_params")
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_resource(resource = nil)
        resource ||= resource_class.find(params[:id])
        instance_variable_set("@#{resource_name}", resource)
      end
  end
end  

app/controllers/api/datapoints_controller.rb
module Api

  class DatapointsController < Api::BaseController
    protect_from_forgery with: :null_session

    def create
      @probe = Probe.find_by! serial_number: params.require(:serial)
      set_resource(@probe.probe_datapoints.create(data: JSON.parse(params.require(:data))))
      if get_resource.save
        render :show, status: :created
      else
        render json: get_resource.errors, status: :unprocessable_entity
      end
    end

    def datapoint_params
      params.require(:serial).require(:info)
    end

  end
end

app/controllers/api/probes_controller.rb
module Api

  class ProbesController < Api::BaseController
    skip_before_filter :verify_authenticity_token

    def create
      @probe = Probe.find_by! serial_number: params.require(:serial)
      @probe.user_id = current_user.id
      @probe.save()
      render :show, status: :created
    end

    def datapoint_params
      params.require(:serial).require(:info)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController

  respond_to :html

  def index
  end

  def show
  end

  def new
  end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  respond_to :html

  def index
    @studies = Study.all
  end

  def new
    @study = Study.new
    4.times { @study.instructions.build}
  end

  def edit
    @study = Study.find(params[:id])
    if @study.user != current_user
      redirect_to "/"
      return
    end
    4.times { @study.instructions.build}
  end

  def update
    @study = Study.find(params[:id])
    if @study.user != current_user
      redirect_to "/"
      return
    end
    @study.update(study_params)
    redirect_to action: :show, id: @study.id
  end

  def create
    @study = Study.new(study_params)
    @study.user_id = current_user.id
    @study.save
    current_user.study = @study
    redirect_to action: :show, id: @study.id
  end

  def join
    if !current_user.study
      @study = Study.find(params[:id])
      current_user.study = @study
      current_user.save
      redirect_to action: :show, id: @study.id
    else
      redirect_to "/"
    end
  end

  def leave
    @study = Study.find(params[:id])
    if current_user.study == @study
      current_user.study = nil
      current_user.save
      redirect_to action: :show, id: @study.id
    end
  end

  def show
    @study = Study.find(params[:id])
  end

  private
  def study_params
    params.require(:study).permit(:name, :start, :end, :description, instructions_attributes: [:id, :name, :description])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name)
    params[:controller] == controller_name ? "active" : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? "active" : nil
  end
end

app/helpers/labelling_form_builder.rb
class LabellingFormBuilder < ActionView::Helpers::FormBuilder
  def text_field(attribute, options={})
    label(attribute) + super
  end
end

app/views/dashboards/dashboard_1.html.erb
<div class="row  border-bottom white-bg dashboard-header">
    <div class="col-sm-3">
        <h2>Welcome {Name}</h2>
    </div>
    <div class="col-sm-9">
        <div class="dashboard-header-box">
            <h3>
                {Project Name} timeline
            </h3>
            <p>
                There are {x} days left for this project.
            </p>
            <div class="row text-center">
                
                <div class="col-lg-12">
                    <!-- if participant in a project -->
                    <div class="progress progress-striped">
                        <div style="width: 50%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" role="progressbar" class="progress-bar progress-bar-warning">
                            <span class="sr-only">40% Complete (success)</span>
                        </div>
                    </div>
                    <!-- else show zero state -->
<!--                     <div class="dashboard-header-zero">
                        You are not currently participating in any research projects.  View active projects?
                    </div> -->
                </div>
            </div>
        </div>
    </div>

</div>
<div class="row">
<div class="col-lg-12">
<div class="wrapper wrapper-content">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Project Summary</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-lg-9">
                        <div class="flot-chart">
                            <div class="flot-chart-content" id="flot-dashboard-chart"></div>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <ul class="stat-list">
                            <li>
                                <h2 class="no-margins">2,346</h2>
                                <small>Total orders in period</small>
                                <div class="stat-percent">48% <i class="fa fa-level-up text-navy"></i></div>
                                <div class="progress progress-mini">
                                    <div style="width: 48%;" class="progress-bar"></div>
                                </div>
                            </li>
                            <li>
                                <h2 class="no-margins ">4,422</h2>
                                <small>Orders in last month</small>
                                <div class="stat-percent">60% <i class="fa fa-level-down text-navy"></i></div>
                                <div class="progress progress-mini">
                                    <div style="width: 60%;" class="progress-bar"></div>
                                </div>
                            </li>
                            <li>
                                <h2 class="no-margins ">9,180</h2>
                                <small>Monthly income from orders</small>
                                <div class="stat-percent">22% <i class="fa fa-bolt text-navy"></i></div>
                                <div class="progress progress-mini">
                                    <div style="width: 22%;" class="progress-bar"></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Recent comments</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content no-padding">
            <ul class="list-group">
                <li class="list-group-item">
                    <p><a class="text-info" href="#">Alan Marry</a> I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 1 minuts ago</small>
                </li>
                <li class="list-group-item">
                    <p><a class="text-info" href="#">Stock Man</a> Check this stock chart. This price is crazy! </p>
                    <div class="text-center m">
                        <span id="sparkline8"></span>
                    </div>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 2 hours ago</small>
                </li>
                <li class="list-group-item">
                    <p><a class="text-info" href="#">Kevin Smith</a> Lorem ipsum unknown printer took a galley </p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 2 minuts ago</small>
                </li>
                <li class="list-group-item ">
                    <p><a class="text-info" href="#">Jonathan Febrick</a> The standard chunk of Lorem Ipsum</p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 1 hour ago</small>
                </li>
                <li class="list-group-item">
                    <p><a class="text-info" href="#">Alan Marry</a> I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 1 minuts ago</small>
                </li>
                <li class="list-group-item">
                    <p><a class="text-info" href="#">Kevin Smith</a> Lorem ipsum unknown printer took a galley </p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 2 minuts ago</small>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Your Probe Data</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="flot-chart">
                <div class="flot-chart-content" id="flot-line-chart"></div>
            </div>
            <a href="#">Go to Probe Page</a>
        </div>
    </div>
</div>

</div>
</div>
</div>
        </div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function() {

    setTimeout(function() {
        toastr.options = {
            closeButton: true,
            progressBar: true,
            showMethod: 'slideDown',
            timeOut: 4000
        };
        toastr.success('Responsive Admin Theme', 'Welcome to INSPINIA');

    }, 1300);

    $(".bar_dashboard").peity("bar", {
        fill: ["#1ab394", "#d7d7d7"],
        width: 100
    })

    $("#sparkline8").sparkline([5, 6, 7, 2, 0, 4, 2, 4, 5, 7, 2, 4, 12, 14, 4, 2, 14, 12, 7], {
        type: 'bar',
        barWidth: 8,
        height: '150px',
        barColor: '#1ab394',
        negBarColor: '#c6c6c6'
    });

    var updatingChart = $(".updating-chart").peity("line", { fill: '#1ab394', stroke: '#169c81', width: 64 })

    setInterval(function () {
        var random = Math.round(Math.random() * 10)
        var values = updatingChart.text().split(",")
        values.shift()
        values.push(random)

        updatingChart
                .text(values.join(","))
                .change()
    }, 1000);

    var data1 = [
        [0, 4], [1, 8], [2, 5], [3, 10], [4, 4], [5, 16], [6, 5], [7, 11], [8, 6], [9, 11], [10, 30], [11, 10], [12, 13], [13, 4], [14, 3], [15, 3], [16, 6]
    ];
    var data2 = [
        [0, 1], [1, 0], [2, 2], [3, 0], [4, 1], [5, 3], [6, 1], [7, 5], [8, 2], [9, 3], [10, 2], [11, 1], [12, 0], [13, 2], [14, 8], [15, 0], [16, 0]
    ];
    $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
        data1, data2
    ],
            {
                series: {
                    lines: {
                        show: false,
                        fill: true
                    },
                    splines: {
                        show: true,
                        tension: 0.4,
                        lineWidth: 1,
                        fill: 0.4
                    },
                    points: {
                        radius: 0,
                        show: true
                    },
                    shadowSize: 2
                },
                grid: {
                    hoverable: true,
                    clickable: true,
                    tickColor: "#d5d5d5",
                    borderWidth: 1,
                    color: '#d5d5d5'
                },
                colors: ["#1ab394", "#1C84C6"],
                xaxis: {
                },
                yaxis: {
                    ticks: 4
                },
                tooltip: false
            }
    );
    
    var barOptions = {
        series: {
            lines: {
                show: true,
                lineWidth: 2,
                fill: true,
                fillColor: {
                    colors: [{
                        opacity: 0.0
                    }, {
                        opacity: 0.0
                    }]
                }
            }
        },
        xaxis: {
            tickDecimals: 0
        },
        colors: ["#1ab394"],
        grid: {
            color: "#999999",
            hoverable: true,
            clickable: true,
            tickColor: "#D4D4D4",
            borderWidth: 0
        },
        legend: {
            show: false
        },
        tooltip: true,
        tooltipOpts: {
            content: "x: %x, y: %y"
        }
    };
    var barData = {
        label: "bar",
        data: [
            [1, 34],
            [2, 25],
            [3, 19],
            [4, 34],
            [5, 32],
            [6, 44]
        ]
    };
    $.plot($("#flot-line-chart"), [barData], barOptions);
});

</script>

<% end %>

app/views/dashboards/index.html.erb
<div class="row  border-bottom white-bg dashboard-header">
  <div class="col-sm-12">
    <h2>Dashboard</h2>
  </div>
</div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content">
      <% if current_user and current_user.study %>
        <div class="row">
          <div class="col-lg-12">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>Project Goal</h5>
                <div class="ibox-tools">
                  <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                  </a>
                </div>
              </div>
              <div class="ibox-content">
                <div class="row">
                  <div class="col-lg-12">
                    <h5>Completion {x}%</h5>
                    <div class="progress progress-striped">
                      <div style="width: 50%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" role="progressbar" class="progress-bar progress-bar-warning">
                        <span class="sr-only">{x}% Complete</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>Project Summary</h5>
              </div>
              <div class="ibox-content">
                <div class="row">
                  <div class="col-lg-9">
                    <div class="flot-chart">
                      <div class="flot-chart-content" id="flot-dashboard-chart"></div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <ul class="stat-list">
                      <li>
                        <h2 class="no-margins">2,346</h2>
                        <small>Total orders in period</small>
                        <div class="stat-percent">48% <i class="fa fa-level-up text-navy"></i></div>
                        <div class="progress progress-mini">
                          <div style="width: 48%;" class="progress-bar"></div>
                        </div>
                      </li>
                      <li>
                        <h2 class="no-margins ">4,422</h2>
                        <small>Orders in last month</small>
                        <div class="stat-percent">60% <i class="fa fa-level-down text-navy"></i></div>
                        <div class="progress progress-mini">
                          <div style="width: 60%;" class="progress-bar"></div>
                        </div>
                      </li>
                      <li>
                        <h2 class="no-margins ">9,180</h2>
                        <small>Monthly income from orders</small>
                        <div class="stat-percent">22% <i class="fa fa-bolt text-navy"></i></div>
                        <div class="progress progress-mini">
                          <div style="width: 22%;" class="progress-bar"></div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>Recent comments</h5>
                <div class="ibox-tools">
                  <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                  </a>
                </div>
              </div>
              <div class="ibox-content no-padding">
                <ul class="list-group">
                  <li class="list-group-item">
                    <p><a class="text-info" href="#">Alan Marry</a> I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 1 minuts ago</small>
                  </li>
                  <li class="list-group-item">
                    <p><a class="text-info" href="#">Stock Man</a> Check this stock chart. This price is crazy! </p>
                    <div class="text-center m">
                      <span id="sparkline8"></span>
                    </div>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 2 hours ago</small>
                  </li>
                  <li class="list-group-item">
                    <p><a class="text-info" href="#">Kevin Smith</a> Lorem ipsum unknown printer took a galley </p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 2 minuts ago</small>
                  </li>
                  <li class="list-group-item ">
                    <p><a class="text-info" href="#">Jonathan Febrick</a> The standard chunk of Lorem Ipsum</p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 1 hour ago</small>
                  </li>
                  <li class="list-group-item">
                    <p><a class="text-info" href="#">Alan Marry</a> I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 1 minuts ago</small>
                  </li>
                  <li class="list-group-item">
                    <p><a class="text-info" href="#">Kevin Smith</a> Lorem ipsum unknown printer took a galley </p>
                    <small class="block text-muted"><i class="fa fa-clock-o"></i> 2 minuts ago</small>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="ibox float-e-margins">
              <div class="ibox-title">
                <h5>Your Probe Data</h5>
                <div class="ibox-tools">
                  <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                  </a>
                </div>
              </div>
              <div class="ibox-content">
                <div class="flot-chart">
                  <div class="flot-chart-content" id="flot-line-chart"></div>
                </div>
                <a href="#">Go to Probe Page</a>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="row text-center">
          <div class="col-lg-12">
            You currently have no active projects.  Browse
            <%= link_to studies_path do %>
              <span class="text-info">all active projects</span>
            <% end %>
            .
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">

$(function() {

  setTimeout(function() {
    toastr.options = {
      closeButton: true,
      progressBar: true,
      showMethod: 'slideDown',
      timeOut: 4000
    };
    toastr.success('Responsive Admin Theme', 'Welcome to INSPINIA');

  }, 1300);

  $(".bar_dashboard").peity("bar", {
    fill: ["#1ab394", "#d7d7d7"],
    width: 100
  })

  $("#sparkline8").sparkline([5, 6, 7, 2, 0, 4, 2, 4, 5, 7, 2, 4, 12, 14, 4, 2, 14, 12, 7], {
    type: 'bar',
    barWidth: 8,
    height: '150px',
    barColor: '#1ab394',
    negBarColor: '#c6c6c6'
  });

  var updatingChart = $(".updating-chart").peity("line", { fill: '#1ab394', stroke: '#169c81', width: 64 })

  setInterval(function () {
    var random = Math.round(Math.random() * 10)
    var values = updatingChart.text().split(",")
    values.shift()
    values.push(random)

    updatingChart
        .text(values.join(","))
        .change()
  }, 1000);

  var data1 = [
    [0, 4], [1, 8], [2, 5], [3, 10], [4, 4], [5, 16], [6, 5], [7, 11], [8, 6], [9, 11], [10, 30], [11, 10], [12, 13], [13, 4], [14, 3], [15, 3], [16, 6]
  ];
  var data2 = [
    [0, 1], [1, 0], [2, 2], [3, 0], [4, 1], [5, 3], [6, 1], [7, 5], [8, 2], [9, 3], [10, 2], [11, 1], [12, 0], [13, 2], [14, 8], [15, 0], [16, 0]
  ];
  $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
    data1, data2
  ],
      {
        series: {
          lines: {
            show: false,
            fill: true
          },
          splines: {
            show: true,
            tension: 0.4,
            lineWidth: 1,
            fill: 0.4
          },
          points: {
            radius: 0,
            show: true
          },
          shadowSize: 2
        },
        grid: {
          hoverable: true,
          clickable: true,
          tickColor: "#d5d5d5",
          borderWidth: 1,
          color: '#d5d5d5'
        },
        colors: ["#1ab394", "#1C84C6"],
        xaxis: {
        },
        yaxis: {
          ticks: 4
        },
        tooltip: false
      }
  );

  var barOptions = {
    series: {
      lines: {
        show: true,
        lineWidth: 2,
        fill: true,
        fillColor: {
          colors: [{
            opacity: 0.0
          }, {
            opacity: 0.0
          }]
        }
      }
    },
    xaxis: {
      tickDecimals: 0
    },
    colors: ["#1ab394"],
    grid: {
      color: "#999999",
      hoverable: true,
      clickable: true,
      tickColor: "#D4D4D4",
      borderWidth: 0
    },
    legend: {
      show: false
    },
    tooltip: true,
    tooltipOpts: {
      content: "x: %x, y: %y"
    }
  };
  var barData = {
    label: "bar",
    data: [
      [1, 34],
      [2, 25],
      [3, 19],
      [4, 34],
      [5, 32],
      [6, 44]
    ]
  };
  $.plot($("#flot-line-chart"), [barData], barOptions);
});

</script>

<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Candidate for <a href="http://artik.devpost.com/">Makers Against Drought</a>
    </div>
    <div>
        <strong>Copyright</strong> &copy; 2016
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <% if user_signed_in? %>
        <li class="nav-header">
          <div class="dropdown profile-element">
            <span>
              <img alt="image" class="img-circle" src="<%= image_url 'profile_small.jpg' %>"/>
            </span>
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
              <span class="clear">
                  <span class="block m-t-xs">
                    <strong class="font-bold"><%= current_user.name %></strong>
                  </span>
                  <span class="text-muted text-xs block">Researcher <b class="caret"></b></span>
              </span>
            </a>
            <ul class="dropdown-menu animated fadeInRight m-t-xs">
              <li><a href="">Profile</a>
              </li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path%>
              </li>
            </ul>
          </div>
          <div class="logo-element">
            <a href="#">
              <img alt="image" class="img-circle" src="<%= image_url 'profile_small.jpg' %>"/>
            </a>
          </div>
        </li>
      <% end %>
      <li class="<%= is_active_controller('dashboards') %>">
        <%= link_to root_path do %>
          <i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Dashboard</span>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="<%= is_active_action('project_detail') %>">
          <%= link_to studies_path do %>
            <i class="fa fa-folder-open"></i> <span class="nav-label" data-i18n="nav.appviews">Your Project</span>
          <% end %>
        </li>
      <% end %>
      <li class="<%= is_active_controller('studies') %>">
        <%= link_to studies_path do %>
          <i class="fa fa-th-list"></i> <span class="nav-label" data-i18n="nav.studies">All Studies</span>
        <% end %>
      </li>
      <li class="<%= is_active_controller('probes') %>">
        <%= link_to probes_path do %>
          <i class="fa fa-cog"></i> <span class="nav-label" data-i18n="nav.probes">Probe Settings</span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <% if user_signed_in? %>
          <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">Signed in as {Name}.</span>
        <% else %>
          <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">Welcome to {Project}.</span>
        <% end %>
      </li>

      <li>
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path do%>
            <i class="fa fa-sign-out"></i> Sign out
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do%>
            <i class="fa fa-sign-in"></i> Sign in
          <% end %>
        <% end %>
    </li>
  </ul>
</nav>
</div>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INSPINIA | Responsive admin theme</title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="gray-bg">

<!-- Main view  -->
<%= yield %>


    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>